# Generated by Django 3.1.3 on 2020-11-16 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLineORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=256)),
                ('sku', models.CharField(max_length=256)),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BatchORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=256)),
                ('sku', models.CharField(max_length=256)),
                ('qty', models.IntegerField()),
                ('eta', models.DateTimeField()),
                ('allocated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='control_board.orderlineorm')),
            ],
        ),
    ]
