# Generated by Django 3.1.3 on 2020-11-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineorm',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineorm',
            name='reference',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineorm',
            name='sku',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
