# Generated by Django 3.1.3 on 2020-11-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_board', '0003_auto_20201117_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchorm',
            name='allocated',
        ),
        migrations.CreateModel(
            name='AllocationsORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='control_board.batchorm')),
                ('order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_line', to='control_board.orderlineorm')),
            ],
        ),
    ]
